CREATE DATABASE MONTUE2PM;

USE MONTUE2PM;


CREATE TABLE FIRST_TABLE(
	EMP_ID INT,
	EMP_NAME VARCHAR(20)
);

-- READ THE TABLE
SELECT * FROM FIRST_TABLE;

INSERT INTO FIRST_TABLE VALUES(1,'ROHIT'),(2,'SNEHA'),(3,'AMIT');

-- DML(DATA MANIPULATION LANGUAGE),DDL(DATA DEFINITION LANGUAGE), DQL(Data Query Language)

-- DDL 
-- It is used to define and modify database structure
-- 1. Create, 2. Alter, 3. Drop, 4. Truncate, 5. Rename

-- DML
-- Used to manipulate data, insert, update delete etc.
-- 1. Insert, 2. Update, 3. Delete 4.Merge

-- DQL
-- Used to query database , or may be fetch the data
-- Select


-- --------------------------------------------------------------------------------------------------------

-- DDL 
-- 1. CREATE for creating databases, tables ,views etc
-- How to create database?
-- Syntax
CREATE DATABASE DATABASE_NAME;

-- How to create tables?
-- Syntax
CREATE TABLE NAME_OF_TABLE(
	COL1 INT,
	COL2 VARCHAR(10)
);-- INT AND VARCHAR ARE DATATYPES AND COL1 AND COL2 ARE COLUMNS NAME


-- 2. ALTER WE USED TO MODIFY THE STRUCTURE OF AN EXISTING TABLE(ADD, DELETE OR MODIFY COLUMNS)
ALTER TABLE 
TABLE_NAME
ADD NEW_COLUMN VARCHAR(20); --WE ARE ADDING HERE NEW COLUMN IN OUR TABLE NAMED WITH TABLE_NAME THE TYPE IS GOING TO BE VARCHAR(20)

ALTER TABLE TABLE_NAME ALTER COLUMN COLUMN_NAME VARCHAR(10); -- SQL SERVER
-- ALTER TABLE TABLE_NAME MODIFY COLUMN_NAME VARCHAR(3); -- MYSQL

-- 3. DROP Permanently deletes a table or database;
DROP TABLE TABLE_NAME;
DROP DATABASE DATABASE_NAM;



-- 4. TRUNCATE
-- REMOVE ALL THE RECORDS(ROWS) FROM A TABLE BUT KEEPS THE STRUCTURE INTACT.
TRUNCATE TABLE TABLE_NAME;


-- 5. RENAME
-- CHANGE THE NAME OF AN EXISTING TABLE
EXEC SP_RENAME 'TABLE_ONE','NEW_NAME';

-- RENAME COLUMN
EXEC SP_RENAME 'TABLE_NAME.OLD_COLUMN_NAME','NEW_COLUMN_NAME','COLUMN';

-- RENAME DATABASE
ALTER DATABASE OLD_NAME
MODIFY NAME = NEW_DATABASE_NAME;


-- DDL PRACTICE
USE MONTUE2PM;



-- CREATE OPERATION
CREATE TABLE STUDENT(
	STUDENT_ID INT PRIMARY KEY, -- ALL THE STUDENT ID ARE GOING TO BE UNIQUE AND NOT NULL
	FULL_NAME VARCHAR(20) NOT NULL,
	EMAIL VARCHAR(30) UNIQUE,
	AGE INT,
	MARKS DECIMAL(5,2),
	CITY VARCHAR(50),
);

INSERT INTO LEARNERS(REGISTRATIONNO,FULL_NAME,EMAIL,AGE,MARKS,CITY) 
VALUES(1,'HARSHIT','HARSHIT@EXAMPLE.COM',28,35.43,'DELHI');

-- READ THE DATA
SELECT * FROM LEARNERS;

-- ALTER OPERATION
ALTER TABLE 
STUDENT
ADD PHONE_NUMER VARCHAR(15); -- ADDING THE NEW COLUMN IN TABLE

ALTER TABLE STUDENT ALTER COLUMN CITY VARCHAR(20); -- CHANGING THE DATAYPE

-- RENAME THE TABLE
EXEC SP_RENAME 'STUDENT','LEARNERS';

-- RENAME THE COLUMN
EXEC SP_RENAME 'LEARNERS.STUDENT_ID','REGISTRATIONNO','COLUMN';

-- RENAME THE DATABASE
ALTER DATABASE MONTUE2PM
MODIFY NAME = SQL_BASICS;


-- TRUNCATE(IT IS USED TO REMOVE ALL THE RECORDS FROM TABLE)
TRUNCATE TABLE LEARNERS;

-- DROP TABLE
DROP TABLE LEARNERS;

-- DROP DATABASE
DROP DATABASE SQL_BASICS;
