-- clauses
-- select,from,where,group by,having,order by , limit

CREATE TABLE EMPLOYEES(
	EMP_ID INT PRIMARY KEY,
    EMP_NAME VARCHAR(30),
    SALARY FLOAT,
    DEPARTMENT VARCHAR(23),
    ENGAGEMENT_SCORE DECIMAL(4,2)
);

INSERT INTO EMPLOYEES VALUES
(1,"ROHIT",43000,"SALES",2.4),
(2,"KAMINI",34000,"HR",4.4),
(3,"ROHAN",45000,"SALES",3.8),
(4,"RAJAN",36000,"FINANCE",4.6);

SELECT * FROM EMPLOYEES;

-- WHERE  , IT IS USED TO CHECK THE CONDITION
SELECT 
	*
FROM EMPLOYEES 
WHERE SALARY>40000 OR ENGAGEMENT_SCORE>3;

-- GROUP BY & HAVING (HAVING WORKS WITH GROUP BY TO APPLY THE CONDITION )

-- SALARY DISTIRBUTION BY DEPARTMENT
SELECT 
	DEPARTMENT,
    SUM(SALARY) AS SPENDING
FROM EMPLOYEES
GROUP BY DEPARTMENT
HAVING DEPARTMENT = "HR";

-- ORDER BY (BY DEFAULT ORDER BY APPLIES ASCENDING ORDER)
SELECT 
	* 
FROM EMPLOYEES
ORDER BY SALARY DESC;

-- LIMIT 
-- SHOW TOP 2 EMPLOYEES WITH HIGHEST SALARY

SELECT 
	*
FROM EMPLOYEES
ORDER BY SALARY DESC
LIMIT 2;
