-- CONSTRAINTS 
-- CONSTRAINTS ARE RULES APPLIED TO TABLE COLUMNS TO MAINTAIN DATA INTEGRITY,ACCUARCY, AND RELIABILITY IN DATABASE.


-- PRIMARY KEY, FOREIGN KEY , NOT NULL, CHECK,UNIQUE, DEFAULT and AUTO INCREMENT

-- PRIMARY KEY
CREATE DATABASE PRACTICE;
USE PRACTICE;

CREATE TABLE CUSTOMER(
	ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    EMAIL VARCHAR(40) NOT NULL
);


INSERT INTO CUSTOMER VALUES(3,"NEHA");
INSERT INTO CUSTOMER VALUES(4,"RUDRA");
SELECT * FROM CUSTOMER;

DROP TABLE CUSTOMER;

-- FOREIGN KEY
CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    QUANTITY INT,
    FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMER(ID)
);

INSERT INTO ORDERS VALUES(101,1,4),(102,2,5),(103,1,6),(104,3,7);
INSERT INTO ORDERS VALUES(105,4,6);


-- NOT NULL

CREATE TABLE CUSTOMER(
	ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    EMAIL VARCHAR(40) NOT NULL
); 
INSERT INTO CUSTOMER VALUES(1,"SOHIT","SOHIT@EMAIL.COM");

INSERT INTO CUSTOMER(ID,EMAIL) VALUES(2,"KRISH@EMAIL.COM");

INSERT INTO CUSTOMER(ID,NAME) VALUES(3,"MOHIT");
SELECT * FROM CUSTOMER;

-- CHECK CONSTRAINT

DROP TABLE CUSTOMER;
DROP TABLE ORDERS;
CREATE TABLE CUSTOMER(
	ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    EMAIL VARCHAR(40) NOT NULL,
    AGE INT,
    CHECK(AGE >= 20)
); 

INSERT INTO CUSTOMER VALUES(1,"NAJIMA","HELLO@EMAIL.COM",25);

SELECT * FROM CUSTOMER;
DROP TABLE CUSTOMER;
-- UNIQUE
CREATE TABLE CUSTOMER(
	ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    EMAIL VARCHAR(40) NOT NULL,
    USERNAME VARCHAR(32) UNIQUE,
    AGE INT,
    CHECK(AGE >= 20)
);

INSERT INTO CUSTOMER(ID,NAME,EMAIL,AGE) VALUES(3,"ROHIT","JGFLSDJGLDSA",32);

-- PRIMARY KEY IS COMBINATION OF  ' NOT NULL AND UNIQUE '

-- DEFAULT
CREATE TABLE CUSTOMER(
	ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    EMAIL VARCHAR(40) NOT NULL,
    USERNAME VARCHAR(32) UNIQUE,
    JOBROLE VARCHAR(23) DEFAULT "SALE",
    AGE INT,
    CHECK(AGE >= 20)
);

INSERT INTO CUSTOMER(ID,NAME,EMAIL,USERNAME,AGE) VALUES(1,"HHDSJF","FKJDSHDKJ","JSDJF",23);
INSERT INTO CUSTOMER VALUES(2,"JKGFD","fDSGDSG","FDSCSD","HR",25);
SELECT * FROM CUSTOMER;



-- AUTO INCREMENT

DROP TABLE CUSTOMER;

CREATE TABLE CUSTOMER(
	ID INT AUTO_INCREMENT PRIMARY KEY ,
    NAME VARCHAR(30),
    EMAIL VARCHAR(40) NOT NULL,
    USERNAME VARCHAR(32) UNIQUE,
    JOBROLE VARCHAR(23) DEFAULT "SALE",
    AGE INT,
    CHECK(AGE >= 20)
);

INSERT INTO CUSTOMER(NAME,EMAIL,USERNAME,AGE) VALUES("HGJSD","JFLDS ","FSDGDS",43);
INSERT INTO CUSTOMER(NAME,EMAIL,USERNAME,AGE) VALUES("HGJSD","JFLDS ","FSDGAG",43);
SELECT * FROM CUSTOMER;



-- COMPOSITE PRIMARY
CREATE TABLE STUDENTS(
	STDID INT,
    COURSE_ID INT,
	PRIMARY KEY(STDID,COURSE_ID)
);

INSERT INTO STUDENTS VALUES(2,101);

SELECT * FROM STUDENTS;

