-- Joins
-- Joins are used to connect tables by rows

create database joins;
use joins;

CREATE TABLE CUSTOMER(
	ID INT PRIMARY KEY,
    NAME VARCHAR(30),
    EMAIL VARCHAR(40) NOT NULL
);

insert into customer values(1,"komal","first@email.com"),(2,"Nishu","njdf@email.com");
INSERT INTO CUSTOMER VALUES(4,"RISHI","RISHIG@EMAIL.COM");
CREATE TABLE ORDERS(
	ORDER_ID INT PRIMARY KEY,
    CUSTOMER_ID INT,
    QUANTITY INT
);
insert into orders values(101,1,4),(102,2,5),(103,1,7),(104,3,7);
INSERT INTO ORDERS VALUES(105,5,10);

select * from customer;
select * from orders;


-- innner join,left join,right join, full join, cross join, self join

-- inner join
-- (INNER JOIN WILL FETCH THE COMMON RECORDS)


SELECT 
	*
FROM ORDERS
INNER JOIN CUSTOMER
ON CUSTOMER.ID = ORDERS.CUSTOMER_ID;

-- LEFT JOIN
-- I WILL FETCH ALL THE RECORDS OF LEFT TABLE ALONG WITH COMMON RECORDS
SELECT 
	*
FROM ORDERS
LEFT JOIN CUSTOMER
ON CUSTOMER.ID = ORDERS.CUSTOMER_ID;

-- RIGHT JOIN
-- I WILL FETHC ALL THE RECORDS OF RIGHT TABLE ALONG WITH COMMON RECORDS BUT NO UNCOMMON OF LEFT TABLE

SELECT 
	*
FROM ORDERS O
RIGHT JOIN CUSTOMER C
ON O.CUSTOMER_ID = C.ID;


-- FULL JOIN
SELECT 
	*
FROM ORDERS
LEFT JOIN CUSTOMER
ON ORDERS.CUSTOMER_ID = CUSTOMER.ID

UNION 

SELECT 
	*
FROM ORDERS
RIGHT JOIN CUSTOMER
ON ORDERS.CUSTOMER_ID = CUSTOMER.ID;


-- CROSS JOIN (IT CREATES THE COMBINATION)
SELECT
	*
FROM ORDERS 
CROSS JOIN CUSTOMER;

-- SELF JOIN
CREATE TABLE EMPLOYEE(
	EMP_ID INT,
    EMP_NAME VARCHAR(20),
    MANAGER_ID int
);


INSERT INTO EMPLOYEE VALUES(1,"ROHAN",NULL),(2,"SOHIT",1),(3,"KASHISH",1),(4,"KRISHNA",2),(5,"AMIT",3);

SELECT
	E.EMP_ID,
    E.EMP_NAME,
    E.MANAGER_ID,
    M.EMP_NAME
FROM EMPLOYEE E
LEFT JOIN EMPLOYEE M 
ON E.MANAGER_ID = M.EMP_ID;



	